- name: create directory
  file:
    path: "{{ peer_install_path }}/{{ item }}"
    state: directory
  with_items:
    - 'bin'
    - 'tls'
    - 'msp'
    - 'log'
    - 'data'

- name: upload binary
  notify: restart peer
  copy:
    src: "{{ item }}"
    dest: "{{ peer_install_path }}/bin"
    mode: u=rwx
  with_items:
    - "{{ bin_path }}/peer"

- name: upload msp files 
  notify: restart peer
  copy:
    src: "{{ item }}"
    dest: "{{ peer_install_path }}"
  with_items:
    - "{{ peer_crypto_path }}/{{ ORG_DOMAIN }}/peers/{{ inventory_hostname }}/msp"
    - "{{ peer_crypto_path }}/{{ ORG_DOMAIN }}/peers/{{ inventory_hostname }}/tls"

- name: upload peer config
  notify: restart peer
  template:
    src: "{{ item }}.j2"
    dest: "{{ peer_install_path }}/{{ item }}"
  with_items:
    - core.yaml

- name: upload supervisord config
  notify: update supervisord
  template:
    src: "{{ item }}.j2"
    dest: "{{ peer_install_path }}/{{ item }}"
  with_items:
    - peer.ini   

- name: create link
  notify: update supervisord
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  with_items:
    - { src: "{{ peer_install_path }}/peer.ini", dest: "/etc/supervisord.d/peer.ini" }

- name: upload script 
  copy:
    src: "{{ item }}"
    dest: "{{ peer_install_path }}"
    mode: u=rwx
  with_items:
    - start.sh
    - stop.sh
