- name: set time zone
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  with_items:
    - { src: "/usr/share/zoneinfo/Asia/Shanghai", dest: "/etc/localtime" }

- name: set local
  shell: localedef -i zh_CN  -f UTF-8 zh_CN.UTF-8

- name: install epel
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
    - epel-release

- name: couchdb repo
  copy:
    src:  "{{ item }}"
    dest: "/etc/yum.repos.d/{{ item }}"
  with_items:
    - "apache-couchdb-rpm.repo"

- name: install pkgs
  yum: 
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - supervisor
    - libtool-ltdl
    - golang
    - git
    - couchdb 

- name: upload docker-ce-18.03.1.ce
  copy:
    src:  docker-ce-18.03.1.ce-1.el7.centos.x86_64.rpm
    dest: "/tmp/"

- name: install docker-ce-18.03.1.ce
  yum: 
    name: "/tmp/docker-ce-18.03.1.ce-1.el7.centos.x86_64.rpm"
    state: present

- name: docker daemon config
  file: 
    path: /etc/docker/
    state: directory

- name: docker daemon config
  notify: restart docker
  copy: 
    src: docker_daemon.json
    dest: /etc/docker/daemon.json

- name: start couchdb
  systemd:
      state: started
      name: couchdb

- name: start docker
  systemd:
      state: started
      name: docker

- name: start basic service
  service:
     enabled: yes
     name: "{{ item }}"
     state: started
  with_items:
    - ntpd
    - supervisord
