- name: create directory
  file:
    path: "{{ orderer_install_path }}/{{ item }}"
    state: directory
  with_items:
    - 'bin'
    - 'tls'
    - 'msp'
    - 'log'
    - 'data'

- name: upload binary
  notify: restart orderer
  copy:
    src: "{{ item }}"
    dest: "{{ orderer_install_path }}/bin"
    mode: u=rwx
  with_items:
    - "{{ bin_path }}/orderer"

- name: upload msp files 
  notify: restart orderer
  copy:
    src: "{{ item }}"
    dest: "{{ orderer_install_path }}"
  with_items:
    - "{{ orderer_crypto_path }}/{{ ORG_DOMAIN }}/orderers/{{ inventory_hostname }}/msp"
    - "{{ orderer_crypto_path }}/{{ ORG_DOMAIN }}/orderers/{{ inventory_hostname }}/tls"
    - "{{ channel_path }}/genesisblock"

- name: upload orderer config
  notify: restart orderer
  template:
    src: "{{ item }}.j2"
    dest: "{{ orderer_install_path }}/{{ item }}"
  with_items:
    - orderer.yaml

- name: upload supervisord config
  notify: update supervisord
  template:
    src: "{{ item }}.j2"
    dest: "{{ orderer_install_path }}/{{ item }}"
  with_items:
    - orderer.ini

- name: create link
  notify: update supervisord
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  with_items:
    - { src: "{{ orderer_install_path }}/orderer.ini", dest: "/etc/supervisord.d/orderer.ini" }

- name: upload script 
  copy:
    src: "{{ item }}"
    dest: "{{ orderer_install_path }}"
    mode: u=rwx
  with_items:
    - start.sh
    - stop.sh
